version: '3.4'

networks:
  dev:
    driver: bridge

services:
  # lms:
  #   image: docker.io/library/lms
  #   depends_on:
  #     - "lms_db"
  #     - "rabbitmq" 
  #   container_name: lms-services
  #   ports:
  #     - "8088:8080"
  #   build:
  #     context: ./LoansManagementSystem
  #     dockerfile: Dockerfile
  #   environment:
  #    - ConnectionStrings__DefaultConnection=User ID=admin;Password=admin;Host=lms_db;Port=5432;Database=lms;Pooling=true;
  #    - ASPDOTNET_URLS=http://+:8080
  #   networks:
  #   - dev
    
  # lps:
  #   image: docker.io/library/lps
  #   depends_on:
  #     - "rabbitmq"
  #   container_name: lps-services
  #   ports:
  #     - "8089:8081"
  #   build: 
  #     context: ./LoansProcessingSystem
  #     dockerfile: Dockerfile
  #   environment:
  #    - ASPDOTNET_URLS=http://+:8081
  #   networks:
  #     - dev
      
  lms_db:
    image: postgres:latest  
    container_name: lms_db
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=lms
    ports:
     - "5433:5432"
    restart: always
    volumes:
     - lms-data:/var/lib/postgresql/data
    networks:
     - dev

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672" 
      - "15672:15672"  
    networks:
      - dev

volumes:
  lms-data:
